# Bloco do servidor para redirecionar todo o tráfego HTTP para HTTPS
server {
    listen 80;
    server_name www.lexoffice.com lexoffice.com;

    # Rota para validação do Certbot (Let's Encrypt)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redireciona todo o resto para HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# Bloco do servidor principal para tráfego HTTPS
server {
    listen 443 ssl;
    http2 on;
    server_name www.lexoffice.com lexoffice.com;

    # Caminhos para os certificados SSL (que serão montados via Docker)
    ssl_certificate /etc/letsencrypt/live/www.lexoffice.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.lexoffice.com/privkey.pem;

    # Serve a aplicação React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redireciona as chamadas de API para o container do backend
    location /api {
        proxy_pass http://backend:3333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}